"""empty message

Revision ID: 9ec2a7eb9145
Revises: d9ad6e8a2ceb
Create Date: 2020-03-03 14:58:00.754807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec2a7eb9145'
down_revision = 'd9ad6e8a2ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('danceability', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'danceability')
    # ### end Alembic commands ###
